name: sundephish
description: Full-stack phishing framework built with MFN² stack

publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
